### PR TITLE
Fix now build

### LINKED ISSUE #23: Build example apps for PR review
I'd like to set something up to build the example app in PRs. It makes it quick and easy to review dependency updates like #21.

I did something similar in another project. The example app doesn't look as nice as this one, but you can see how it gets built and linked to from the PR: paulmelnikow/react-boxplot#49

That's using Zeit Now, which is a pretty easy way to go, though there are other options like Netlify.

If you'd like to try the Zeit route, the easiest way to start is to create an account at http://zeit.co/ and turn on the GitHub integration. You can limit which repos it gets access to.

### PR DESCRIPTION
**Pull request by paulmelnikow**
Fix #23

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Opened https://spectrum.chat/?t=40c55f66-f488-4082-97b2-164e79bf3257

**Comment by paulmelnikow** [comment]
The Now build is working correctly now, however the example app is broken. I can reproduce the problem locally:

```js
Uncaught (in promise) TypeError: Cannot read property 'createClass' of undefined
    at Object.execute (ReactEditableSvgLabel.js:5)
    at doExec (s.js:330)
    at postOrderExec (s.js:326)
    at s.js:288
```

Not sure when that started. Let's merge this and fix in a follow-on.

**Comment by paulmelnikow** [comment]
I thought so at first, though it's `React` which is undefined, not `createClass`, and this build is using React 15.

I merged the rest of the tooling updates – oops, except one left: #29. When that's in, could you merge master into #26 and then we can see where we're at?

**Comment by mathisonian** [comment]
Just merged master into #26

**Pull request merged**
